//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Play
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Play()
        {
            this.Repertoire = new HashSet<Repertoire>();
            this.Tour = new HashSet<Tour>();
            this.Trupe = new HashSet<Trupe>();
        }
    
        public int PlayID { get; set; }
        public string PlayName { get; set; }
        public int PlayGanreID { get; set; }
        public int PlayRatingID { get; set; }
        public string PlayAuthor { get; set; }
        public string PlayImage { get; set; }
        public bool PlayPushkinCard { get; set; }
        private string currentImagePath = "";
        public string PushkinCardString
        {
            get
            {
                if (PlayPushkinCard == true)
                {
                    return "Пушкинская карта!";
                }
                else
                {
                    return string.Empty;
                }
            }

        }
        public DateTime? NearestData
        {
            get
            {
                if (Repertoire == null || Repertoire.Count == 0)
                    return null;

                var now = DateTime.Now;

                // Преобразуем в список для работы с LINQ
                var repertoireList = Repertoire.ToList();

                var futurePerformances = repertoireList
                    .Where(r => r.RepertoireData.HasValue &&
                               r.RepertoireData.Value >= now)
                    .OrderBy(r => r.RepertoireData)
                    .FirstOrDefault();

                return futurePerformances?.RepertoireData;
            }
        }
        public string NearestDataFormatted
        {
            get
            {
                return NearestData.HasValue ?
                       NearestData.Value.ToString("dd.MM.yyyy") :
                       "Не запланировано";
            }
        }



        public int PlayDuration { get; set; }
        public string PlayCountry { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repertoire> Repertoire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trupe> Trupe { get; set; }
    }
}
