//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Repertoire
    {
        public int RepertoireID { get; set; }
        public int RepertoirePlayID { get; set; }
        public Nullable<System.DateTime> RepertoireData { get; set; }
        public Nullable<System.TimeSpan> RepertoireTime { get; set; }
        public decimal RepertoireCost { get; set; }



        public virtual Play Play { get; set; }
    }
}
