//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeatrDBEntities2 : DbContext
    {

        private static TeatrDBEntities2 _context;

        public static TeatrDBEntities2 GetContext()
        {
            if(_context == null)
                _context = new TeatrDBEntities2();
            return _context;
        }

        public TeatrDBEntities2()
            : base("name=TeatrDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Play> Play { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Repertoire> Repertoire { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Trupe> Trupe { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
