//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int TourID { get; set; }
        public string TourName { get; set; }
        public System.DateTime TourDateStart { get; set; }
        public System.DateTime TourDateEnd { get; set; }
        public string TourPlace { get; set; }
        public int TourPlayID { get; set; }
    
        public virtual Play Play { get; set; }
    }
}
