//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trupe
    {
        public int TrupeID { get; set; }
        public int TrupeWorkerID { get; set; }
        public int TrupePlayID { get; set; }
        public string TrupeRole { get; set; }
    
        public virtual Play Play { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
