//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Trupe = new HashSet<Trupe>();
        }
    
        public int WorkerID { get; set; }
        public string WorkerName { get; set; }
        public string WorkerLastName { get; set; }
        public string WorkerPatronic { get; set; }
        public System.DateTime WorkerBirthDay { get; set; }
        public System.DateTime WorkerHiring { get; set; }
        public System.DateTime WorkerExp { get; set; }
        public int WorkerGenderID { get; set; }
        public int WorkerPostID { get; set; }
        public string WorkerAddress { get; set; }
        public string WorkerPhone { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Posts Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trupe> Trupe { get; set; }
    }
}
